### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by woubuc** [woubuc/project-cleanup#3]
The code currently doesn't contain any tests. We should try to add some tests (unit or otherwise), to ensure that later changes don't break existing behaviour.

This will likely include some discussion about testability, and possibly restructuring the code.

**Comment by razorheadfx** [comment]
Way I see it the way to go would be to create a way of mocking the main project types (node.js, cargo etc) in a temporary directory and checking whether the output of 
https://github.com/woubuc/project-cleanup/blob/6acdce321c5f57ef6068a8bc913fa6021762dfc0/src/filter_paths.rs#L19-L48
is what we would expect.

Question is whether you would run that in CI for every PR or manually e.g. from a Dockerfile for every minor release.

**Comment by woubuc** [comment]
I think that would be a good start. Ideally, tests would run in a CI environment on every push and submitted PR, to stay on top of any errors and regressions.

If you're interested in contributing, I've rewritten a large portion of the program to make more use of threading to improve speed, so you can check out the latest version on the `dev/threading` branch. Although to be fair, I haven't given much thought to testing for the rewrite either.

**Comment by woubuc** [comment]
I've added a bunch of unit tests and set up automated testing on every push & PR through Github Actions. I'm gonna close this issue now, since adding more tests and refining the existing tests will just be an ongoing process.
