### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [woubuc/project-cleanup#4]
Hi
I'm Chimzy, a Logo/Icon designer... Just saw your amazing project and I really like the project idea. I want to help create a Logo/Icon for your project as my Free Contribution and my love for contributing to awesome open source projects...

Working on some idea concepts and I will update it here so you can give me your feedback on the design and also suggest any tweaks or changes you want to satisfy your needs.

Will really appreciate your response
Regards!

**Comment by woubuc** [comment]
That would be pretty cool! I always welcome contributions of any kind (though I did not expect this one) 😄

**Comment by chimzycash** [comment]
Really appreciate your quick response... would get the concept ready and share them here for your feedback

**Comment by chimzycash** [comment]
Hi... here is my logo idea concept... You can give your feedback and also share your preferred Logo Color of choice to suit your needs...

![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/59890590-86c0c280-93c9-11e9-9585-cbb3ab41bb5d.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/59890591-86c0c280-93c9-11e9-94fa-8e86d90ca47d.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/59890592-87595900-93c9-11e9-8ff2-f0c0631eb88b.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/59890593-87595900-93c9-11e9-84e0-51b9e88fe67f.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/59890594-87f1ef80-93c9-11e9-988c-ce8b4e0fe4c3.jpg)
![LOGO DESIGN_PROJECT CLEANUP_idea concept_NEW](https://user-images.githubusercontent.com/37814297/59890595-87f1ef80-93c9-11e9-91ec-5dc74cb23fc6.jpg)

**Comment by woubuc** [comment]
That was fast, and the logo looks nice! Gonna do my best to give some good feedback here.

I like the concept of the logo, but I'm personally not a fan of the "generic" blue colour you used here. Maybe it would look better in a "fresh" green / yellow colour? Something [in this direction](http://prntscr.com/o4u2ad) perhaps, what do you think? (screenshot from Google image results so maybe don't use that specifically, just to give an idea). I'm not sure if those colours would work with this design though. If you have other colour suggestions, I'd love to see them.

Other than that, I think maybe the text needs a little more attention. I like how it presents with the icon on the left and the logo on the right (the topmost design), but the height of the text vs the height of the icon seems slightly mismatched / misaligned. There are several horizontal lines in the icon, but none of them match those of the text, and the text isn't aligned with the top or bottom of the icon either. So maybe you could take another look at that? It's a minor issue though.

Lastly, I'm not 100% on the font you used, I think the rounded corners clash a little bit with the straight edges and hard corners of the icon (especially the very sharp and geometric letter P in the logo doesn't match the style of the text at all). Is there a specific reason you chose a rounded font here?

So overall I really like the logo, just needs a different colour and some finetuning I think.

**Comment by chimzycash** [comment]
I really appreciate your amazing feedback ... Would make the tweaks and changes

**Comment by chimzycash** [comment]
Made the changes and went with a bit of a fresh yellowish green color... For changed the font to something that feels more like a hybrid of flat edges and also has some curves to it to match with the curvy top part of the Logo Icon...

![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/59928518-dab5c080-9436-11e9-9702-8f4f263cf720.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/59928519-db4e5700-9436-11e9-95dc-c29095c2e11d.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/59928521-db4e5700-9436-11e9-8115-7aeb11989288.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/59928523-dbe6ed80-9436-11e9-891b-ffee2275eb23.jpg)
![LOGO DESIGN_PROJECT CLEANUP_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/59928525-dbe6ed80-9436-11e9-8eb1-133d0e5100ee.jpg)

**Comment by woubuc** [comment]
Looks great, I like it! Feel free to open a PR to add this logo as an svg in the repo (and maybe add it to the readme as well).

**Comment by chimzycash** [comment]
Prepared the files and I created a Pull Request containing the files.

**Comment by woubuc** [comment]
Awesome work mate, thanks!

**Comment by chimzycash** [comment]
Here is the Google Drive link containing the Logo files and the vector files

https://drive.google.com/drive/folders/12pQYqQH-F_gbt01MhzqLZvJE4nMRRTIi?usp=sharing
