### ISSUE TITLE
Support for NativeScript projects

### ISSUE THREAD

**Issue by NathanaelA** [woubuc/project-cleanup#8]
How interested in a PR to add other npm infrastructure; or would you rather I maintain my own fork.

**Comment by woubuc** [comment]
What do you mean by 'other npm infrastructure'? The tool currently cleans `node_modules` and `.cache` directories in npm projects.

Generally speaking, PRs are always welcome as long as you can explain why you need the added features.

**Comment by NathanaelA** [comment]
I do a lot of NativeScript development.   It not only does a node_modules; but it also has a couple other directories that is all generated and can sometimes be more massive than the node_modules.   

So this would be adding code to deal with the extra directories that are generated in addition to the node_modules.    :grinning:       I'm going to be adding the code to this in the next couple day  -- if it is for a PR; I'm a bit more "clean" and have a lot more error checking.   If it is for me, I'll probably just hack something quick and dirty.  :grinning:

**Comment by woubuc** [comment]
That sounds great for a PR, go ahead! You should be able to add the directories to delete pretty easily in `src/find/identify.rs`.

**Comment by woubuc** [comment]
I never got a PR, were you still planning to do this @NathanaelA?

In any case, if you just want a custom configuration for your project, check out the new feature added for v0.7 - you can [create a `.cleanuprc` file](https://github.com/woubuc/project-cleanup/blob/master/README.md#custom-rules) in your project directory that lists all the directories that should be cleaned.

You can find an RC release of v0.7.0 on the [releases page](https://github.com/woubuc/project-cleanup/releases), let me know if it works for you!

If you still want to submit a PR to add these rules to the application, I will gladly accept it. Better defaults will improve things for all users. But I'll close this issue for now.
